### ISSUE TITLE
Box content sdk authentication failed error

### ISSUE THREAD

**Issue by paragchandra** [box/box-android-sdk#208]
This is a dupe of Issue #183. I don't see any successful resolution in that ticket, so I'm reopening it. Please let me know what to use for the redirect URL, as I have tried the suggestions in the linked issue and I continue to get the same pop-up error.

**Comment by doncung** [comment]
You need a redirect URL in the SDK that matches what you have set at developers.box.com in the settings page that has your api key, secret, etc... You cannot use a scheme as the Android webview will treat that as an error. I'd suggest "https://app.box.com/static/sync_redirect.html" as our application uses that but any http/https scheme should also work. 
You will not be able to use the same settings for the redirect URL for iOS and Android due to the custom scheme. Therefore you may need a different api key for Android.

Please let me know if you are continuing having issues.

**Comment by paragchandra** [comment]
Thanks for your reply. I understand now that the redirect_uri cannot be
arbitrary, but must match what has been set in the developer portal for the
application of interest. However, this means that if I change the
redirect_uri in the portal, then all existing installations of my
application, on both iOS and Android, will now break because the
redirect_uri no longer matches. I have verified this behavior, but just
want to confirm with you that this is expected.

I remember the other suggestion you had, which was to essentially modify
the Box SDK's WebViewClient such that it ignores the invalid scheme error.
I have implemented this change, and it has the desired effect for me: I can
continue to use my existing iOS-specific redirect_uri without getting the
unwanted error Toast on Android. Are there any undesirable side effects you
can think of if I go down this road?

**Comment by doncung** [comment]
It will probably be alright for current versions of Android, but it's hard to say how future proof such a work around is as Android is treating it as an error. Future versions may be more strict for instance I believe in API 23 they added a new version of onReceivedError.

Since your problem is resolved, I'll close this issue. Please let me know if you do run into any issues with the work around.
