### ISSUE TITLE
If multiple identical accounts are added, calling session.logout() on any of them logs them all out

### ISSUE THREAD

**Issue by paragchandra** [box/box-android-sdk#228]
My application enables users to add multiple Box accounts and work with them concurrently. What I want to do is prevent the user from inadvertently adding two or more instances of the _exact same_ account, e.g. same user ID. However, because control is given over to the Box SDK once I call BoxSession.authenticate(), I can't actually detect this condition until _after_ onAuthCreated is invoked, at which time the duplicate account instance has already been added. What I do in my app now is check if there is already a Box account with a matching user ID, and if so, invoke BoxSession.logout() on that second instance. What I've observed is that now _both_ BoxSessions are logged out, because when I try to interact with the original BoxSession, the user is prompted to reenter his credentials.

Perhaps this is by design, but if so, what would be your recommendation for detecting and preventing a user from accidentally adding multiple instances of the exact same account?

**Comment by doncung** [comment]
Hi paragchandra, The sdk is designed to avoid letting users add multiple instances of the same account. 
This is done in the BoxAuthentication class which uses a hashmap based on user id. Therefore if a user logs in again with the same account, all it should do is update the stored access information for that user. Any session that is holding onto old information should either get notified by the BoxAuthentication singleton, or if it is recreated with old information should get updated when it is used to make an api call.

The login process is also controlled such that there is only one account that is in the process of being logged into at any one period of time. If you are seeing otherwise, if you can give me a method to reproduce I can try to fix the issue.

**Comment by doncung** [comment]
Closing this for now. If you are seeing different behavior please feel free to reopen or create a new issue.
