### ISSUE TITLE
How to share BoxSession between activity and intent service

### ISSUE THREAD

**Issue by kkontus** [box/box-android-sdk#249]
Hi all, 

I have a question regarding an issue that I'm not sure how to handle with your API. I have an activity (BoxActivity) where user should login to his Box account (that activity will only have a login button which will use BoxSession and session listener as shown in your examples). After user is successfully logged in he will go to another activity where he can do some operations (select files, images, etc on ) and push them to his Box account using IntentService. The problem is: how can I share existing session or reuse access token to create new session which is needed to create new BoxApiFolder instance inside IntentService?

Thank you.

**Comment by doncung** [comment]
If you only have a single user at a time just create a new BoxSession. The
constructor will fill the session with the info for the last logged in
user. For multiple users you will need to provide the user id for the
session.

**Comment by kkontus** [comment]
Ok, I tested it and it seems fine. I have another question, how can I check if session is still valid, I'm not sure if code below is ok for this. I want to check if session is valid (in that case button should have Log out text), and if it is not then change button text to Log in.

``` 
BoxAuthentication.BoxAuthenticationInfo info = BoxAuthentication.getInstance().getAuthInfo(userId, BoxActivity.this);
  if (info.accessToken() != null) {
         btnAuth.setText("Log out");
         mSession.logout();
  } else {
        btnAuth.setText("Log in");
        configureClient();
        initSession();
  }```

**Comment by doncung** [comment]
The only way to know for sure if a session is invalid is getting an
exception from the server when using it. The sdk has logic to refresh the
session when the token expires, but there are cases such as an admin logout
where the refresh token becomes invalid. Generally you should not need to
worry about this case and just need to call the session's authenticate
method in your activity. If the user has not logged in this will launch ui
to get them to do so, otherwise it will just notify listeners attached to
the session.

On Feb 12, 2017 1:25 PM, "Kristijan Kontus" <notifications@github.com>
wrote:

Ok, I tested it and it seems fine. I have another question, how can I check
if session is still valid, I'm not sure if code below is ok for this. I
want to check if session is valid (in that case button should have Log out
text), and if it is not then change button text to Log in.

BoxAuthentication.BoxAuthenticationInfo info =
BoxAuthentication.getInstance().getAuthInfo(userId, BoxActivity.this);
  if (info.accessToken() != null) {
         btnAuth.setText("Log out");
         mSession.logout();
  } else {
        btnAuth.setText("Log in");
        configureClient();
        initSession();
  }```

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/box/box-android-sdk/issues/249#issuecomment-279250417>,
or mute the thread

**Comment by kkontus** [comment]
Ok, thank you a lot, I can make that check as you proposed. I just wanted to check if there is a way to do this since IntentService will handle uploading in background so I need a way to notify user if session is not available. Thank you for your prompt response. I will close the issue.
