### ISSUE TITLE
err_unknown_url_scheme while authenticating

### ISSUE THREAD

**Issue by bialek** [box/box-android-sdk#277]
Hi,

This error appears after I granted permission to the app. Everything works, I can list my documents but this error message is annoying, what can cause it?

**Comment by doncung** [comment]
If this is after login, it is likely due to the redirect url you are using
not being recognized by the webview.

**Comment by bialek** [comment]
Ok, but what can I do with it? redirect url is set to boxsdk-key://boxsdkoauth2redirect on the app.box.com site.

**Comment by doncung** [comment]
Either use a standard redirect url such as an https:// or modify the
webview and catch the exception.

**Comment by bialek** [comment]
I think I cannot change this redirect url (is it not required such by box?). I don't use webview directly, only call authenticate method on session object.

**Comment by doncung** [comment]
We handle all the webview logic for you in the app though we assume it is of a type we can handle. The redirect url is set on the developers.box.com site. Are you using the same api key/secret for an iOS application, I believe they use a different scheme due to the way apple webviews work. One possibility is you can create a separate api key and secret for your android application which has a https:// or http:// redirect url (you can use our sdk's default for instance). 
The other possibility requires referencing our sdk by submodule/branching. Basically it involves overriding the error handling in the oauthwebview so that it ignores the "err_unknown_url_scheme" you are seeing. We are hesitant to add such logic ourselves due to the possibility we may be suppressing a real error.

**Comment by bialek** [comment]
Thank you for suggestion, I will try this.
