### ISSUE TITLE
It's possible to log out when the user is offline

### ISSUE THREAD

**Issue by MaksimDmitriev** [box/box-android-sdk#281]
Hello.

My device is Nexus 5 with Android 6.0.1. I installed box-content-sample from https://github.com/box/box-android-sdk to my device.

I logged in to my developer's account on my device. I turned off Wi-Fi on my device and then pressed "Log out" on the options menu. I expected to see something like "Unable to log out. Please check your Internet connection." However, I opened the options menu and saw the "Log in" item. 

Best Regards,

MAKSIM

**Comment by dblankety** [comment]
Being able to logout at any time is by design. We just delete all
authentication information in that scenario. The calls to the server to
remove them however will fail, but it is a trade off for better user
experience.

**Comment by doncung** [comment]
Being able to logout at any time is by design. We just delete all
authentication information in that scenario. The calls to the server to
remove them however will fail, but it is a trade off for better user
experience as we do not want users to have to wait till they have a connection to log out.
There is a BoxRevokeAuthRequest class if you want to ensure the server side logout succeeds before the authentication information is removed.
