### ISSUE TITLE
Authentication Failed, Contact admin to authorize this device

### ISSUE THREAD

**Issue by nsonje** [box/box-android-sdk#318]
I am new to Box SDK, I am using this repo in Android Studio and installed the box-sample on my android device. Before that, I copied the Client ID of my developer account in the MainActivity class. I also, authorized this app in my settings.
But, after successfully, authenticating the user, password, it is giving the following error -
![screenshot_2017-11-12-17-42-17](https://user-images.githubusercontent.com/3501522/32698799-4c16d2f2-c7d1-11e7-9ccb-2ec190e942f3.png)

What should I do now? How to authorize the device?

**Comment by nsonje** [comment]
There is no option to authorize a particular device in Settings.

**Comment by doncung** [comment]
Can you check your logcat? There is a static for debugging in settings in
BoxConfig. The log should provide a more precise reason for the failure.
Also what kind of account are you testing with? There are enterprise
accounts that have strict requirements and potentially can disable all
applications except for those the admin trusts.

On Nov 12, 2017 4:17 AM, "nsonje" <notifications@github.com> wrote:

There is no option to authorize a particular device in Settings.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/box/box-android-sdk/issues/318#issuecomment-343733085>,
or mute the thread

**Comment by doncung** [comment]
So after some investigation it looks like some accounts  don't work well
with the get users call we make on initial login with all fields requested.
Can you try the latest code from master or reference the the snapshot
4.99.60-SNAPSHOT?
I think that may solve your issue.
