### ISSUE TITLE
Not getting BoxFolder.createFromIdAndName in Boxfolder class

### ISSUE THREAD

**Issue by Ankurjain30** [box/box-android-sdk#319]
below is my list of content being used for compile for box integration.

compile 'com.box:box-java-sdk:2.1.1'
    compile 'com.box:box-android-sdk:3.0.2'
    compile 'com.box:box-android-browse-sdk:1.1.1'
    compile 'com.eclipsesource.minimal-json:minimal-json:0.9.1'

My BoxFolder class is different and extending to BoxItem instead of BoxCollaborationItem and i did not get required methods too.

pls guide what to do.

**Comment by doncung** [comment]
We do not use the box java sdk. It is likely the class you are using is
coming from there.

**Comment by Ankurjain30** [comment]
i removed that and even now, I m getting the same error.

**Comment by doncung** [comment]
I see. You maybe on an older version of the sdk. Since you are taking in
browse the content sdk maybe coming from there. I think the content sdk is
on 4 something.  While the latest browse is 2 something.

**Comment by Ankurjain30** [comment]
Can you help me as I did not able to locate latest versions.

**Comment by doncung** [comment]
Try version 2.0.3 of browse. You can remove the content sdk reference.

On Nov 13, 2017 10:56 PM, "Ankurjain30" <notifications@github.com> wrote:

Can you help me as I did not able to locate latest versions.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/box/box-android-sdk/issues/319#issuecomment-344163539>,
or mute the thread

**Comment by Ankurjain30** [comment]
Thanks it worked.
