### ISSUE TITLE
JWT authentication with Android

### ISSUE THREAD

**Issue by AkashVyasCygnet** [box/box-android-sdk#348]
Hello, 

I need to integrate Box sdk with Android application where i need to do authorization with JWT authentication but in Android SDK i am not able to find the way for it.

Can you please help me asap?
Thanks in advance.

**Comment by doncung** [comment]
Jwt authentication is meant to hook into your own server endpoint and
database. The idea is users login to your site/app at which point you
create a new box app user or reuse an existing user associated to that
login. Your server endpoint on getting authentication it expects returns a
new box authentication token. The android sdk for its part has a
refreshprovider that you implement which will make a call to that endpoint
when it needs a new access token.
For the server implementation we have a java sdk, and a few others that
have the logic. Basically you just need to remember what box users were
created for your users.

**Comment by AkashVyasCygnet** [comment]
Thanks for the quick reply doncung !!

**Comment by doncung** [comment]
The user must login at some point either through your UI or through our UI. Our UI is used by default unless you make use of the refresh provider logic in which you need to implement the RefreshProvider interface to make calls to your JWT server end point or show your own login activity. JWT is not implemented inside of the Android SDK since the device is not secure enough to hold onto the token.

**Comment by AkashVyasCygnet** [comment]
Thanks, @doncung for information.

Can you please share sample code to use own login UI to do login to Box? Is there any APIs provided by Box to do LogIn? Please share details document if possible.

**Comment by doncung** [comment]
There is a sample application in the link below on creating an app user.
There is documentation and some comments.

https://github.com/box/box-java-sdk




On Feb 25, 2018 9:54 PM, "AkashVyasCygnet" <notifications@github.com> wrote:

Thanks, @doncung <https://github.com/doncung> for information.

Can you please share sample code to use own login UI to do login to Box? Is
there any APIs provided by Box to do LogIn? Please share details document
if possible.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/box/box-android-sdk/issues/348#issuecomment-368397751>,
or mute the thread
