### ISSUE TITLE
Upgrade to TLS 1.1 or Higher before June 15

### ISSUE THREAD

**Issue by adunayak** [box/box-android-sdk#366]
Can't change the base url using Android SDK.

**Comment by seema-at-box** [comment]
Could you please elaborate on what you are trying to do.

**Comment by adunayak** [comment]
We are using BOX android SDK in our application. We are supporting from API level 16. 

Since we have many users below API level 20 we can't update to API level 20 as of now. So we wanted to confirm Box integration works without failure on android devices above 20.  

As per documents we can test for TLS 1.1 support using test base URL. But I could not find the API to change the base URL in SDK. Please suggest something to make sure Box integration works on devices above API level 20.

**Comment by doncung** [comment]
The base URL cannot be changed dynamically, however if you fork or clone the repo all urls are contained within BoxConstants.java.

**Comment by doncung** [comment]
I have created a pull request that can support users below 20:
https://github.com/box/box-android-sdk/pulls

**Comment by jitender20dec** [comment]
I also have same issue. I was using box version 3.0.2 from a long time. I am using box sdk version 4.0.11 (com.box:box-android-sdk:4.0.11) in my android app now. And the Redirect URI is myapp://demoApp. It is working fine. But my concern is that last week I got an email from box that I need to change the base url to "https://api.box.com/2.0". In my app I am not using any base url. But inside the box sdk, there is a class BoxConstants.java which contains baseurl as "https://api.box.com/2.0". What changes do I need to make in App so that users can get uninterrupted services in future.

**Comment by adunayak** [comment]
@jitender20dec Use the SDK v4.2.0(https://github.com/box/box-android-sdk/releases). No changes required. 

@doncung Thanks for the update.

**Comment by PreciselyAlyss** [comment]
Closing as fixed
