### ISSUE TITLE
SdkUtils.copyStream started to fail about a week ago

### ISSUE THREAD

**Issue by asadis** [box/box-android-sdk#373]
This is only happening for certain files in Box, including the one attached:
[a294b4a3-e73a-4084-ac78-d87815d661a4.txt](https://github.com/box/box-android-sdk/files/2120874/a294b4a3-e73a-4084-ac78-d87815d661a4.txt)

When downloading this particular file via BoxFileApi.getDownloadRequest(OutputStream,String), SdkUtils.copyStream fails during its second loop at outputStream.write(buffer, 0, bufferLength); Unfortunately no exception is thrown and the thread just hangs indefinitely (no timeout either). 

This either only started happening last week or I just started noticing it because my file somehow meets a certain criteria for this method to fail. As you can see, the file is exactly 1 kb, containing a simple JSON string.

Again, I must reiterate that this is only happening with certain files. I'm able to download hundreds of other files before and after this file - using the same code - with no problems. It only trips up on this and a handful of other files for some reason.

Has anyone else experienced this?

**Comment by asadis** [comment]
Hi doncung,

Thanks for the prompt response! This is for a free user. Let me know if I can provide any other metadata to you (breakpoint, stacktrace, etc.) to help solve this.

Thanks!

**Comment by doncung** [comment]
Having a hard time reproducing this tried uploading to a few different accounts including a free user. Can you try uploading this file to a new free account to see if you can reproduce. If you can it's less likely to be a server side issue. (I'm able to download the file after uploading on my end). 
If you can reproduce can you add the code you are using to make this call? Are you adding any fields to your request or doing anything else I would need to mimic? Also can you let me know what the OS of your device is in case this is device dependent?

**Comment by asadis** [comment]
Doncung,

I've created a simpler version of my line-of-business app to reproduce the issue. You can find it here:

https://github.com/devuserjklsemi/BoxTest

Using this simple app (I've tested it on a Motorola w/ Android 6.0 and a Samsung w/ Android 7.1.1), I'm consistently able to reproduce the download failure when it gets to the file referenced above.

Please email me at dev.user.jklsemi@gmail.com using your official email address if you would like to test this using my temporary credentials and keys. 

Thanks again!

**Comment by doncung** [comment]
Thanks. Looking at your code, I think I have a theory on why it is failing now.
Basically it looks like what you are doing is passing in a PipedOutputStream that is tied to PipedInputStream into the request object. When send is called it tries write everything to the output stream, but it is likely blocked because the the inputstream hasn't been read yet. As such I think the logic is basically deadlocking within the write method.

If all you're trying to do is read out small json files, it's much simpler to use a ByteArrayOutputStream. For something big you would probably want to write it out to a file anyways.
Alternatively you could try fixing your logic by handling your piped streams in another thread such that when the PipedOutputStream is being written to your PipedInputStream blocks. This thread will need to be setup before send is called.

**Comment by asadis** [comment]
You were absolutely right! The intricacies of PipedOutputStream caused a deadlock for only that file while larger files passed right through. I guess I haven't noticed it before because our files were large enough to ensure that the PipedInputStream always instantiated. Thanks so much for the fantastic customer service!
